const CARD = {
    CARD_GET: "CARD_GET",
    CARD_GET_SUCCESS: "CARD_GET_SUCCESS",
    CARD_GET_FAILED: "CARD_GET_FAILED",
    CARD_POST: "CARD_POST",
    CARD_POST_SUCCESS: "CARD_POST_SUCCESS",
    CARD_POST_FAILED: "CARD_POST_FAILED",
    CARD_DELETE: "CARD_DELETE",
    CARD_DELETE_SUCCESS: "CARD_DELETE_SUCCESS",
    CARD_DELETE_FAILED: "CARD_DELETE_FAILED",
    CARD_PUT: "CARD_PUT",
    CARD_PUT_SUCCESS: "CARD_PUT_SUCCESS",
    CARD_PUT_FAILED: "CARD_PUT_FAILED",
};

export default CARD;
