const SITE = {
    SITE_OTP_PUT_V6: "SITE_OTP_PUT_V6",
    SITE_OTP_PUT_V6_SUCCESS: "SITE_OTP_PUT_V6_SUCCESS",
    SITE_OTP_PUT_V6_FAILED: "SITE_OTP_PUT_V6_FAILED",

    SITE_OTP_GET_V6: "SITE_OTP_GET_V6",
    SITE_OTP_GET_V6_SUCCESS: "SITE_OTP_GET_V6_SUCCESS",
    SITE_OTP_GET_V6_FAILED: "SITE_OTP_GET_V6_FAILED",

    // SITE_DELETE_V6: "SITE_DELETE_V6",
    // SITE_DELETE_V6_SUCCESS: "SITE_DELETE_V6_SUCCESS",
    // SITE_DELETE_V6_FAILED: "SITE_DELETE_V6_FAILED",
};

export default SITE;
