const AUTH = {
    LOGOUT: "LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",
    ACC_VERIFICATION_RESEND: "ACC_VERIFICATION_RESEND",
    ACC_VERIFICATION_RESEND_SUCCESS: "ACC_VERIFICATION_RESEND_SUCCESS",
    ACC_VERIFICATION_RESEND_FAILED: "ACC_VERIFICATION_RESEND_FAILED",
};

export default AUTH;
