const CDN = {
    CDN_FIRST: "CDN_FIRST",
    CDN_FIRST_SUCCESS: "CDN_FIRST_SUCCESS",
    CDN_FIRST_FAILED: "CDN_FIRST_FAILED",
    CDN_ENABLE: "CDN_ENABLE",
    CDN_ENABLE_SUCCESS: "CDN_ENABLE_SUCCESS",
    CDN_ENABLE_FAILED: "CDN_ENABLE_FAILED",
    CDN_DISABLE: "CDN_DISABLE",
    CDN_DISABLE_SUCCESS: "CDN_DISABLE_SUCCESS",
    CDN_DISABLE_FAILED: "CDN_DISABLE_FAILED",
    CDN_PUT: "CDN_PUT",
    CDN_PUT_SUCCESS: "CDN_PUT_SUCCESS",
    CDN_PUT_FAILED: "CDN_PUT_FAILED",
    CDN_CACHE: "CDN_CACHE",
    CDN_CACHE_SUCCESS: "CDN_CACHE_SUCCESS",
    CDN_CACHE_FAILED: "CDN_CACHE_FAILED",
};

export default CDN;
