const OPERATION = {
    PHP_RESTART_V2: "PHP_RESTART_V2",
    PHP_RESTART_SUCCESS_V2: "PHP_RESTART_SUCCESS_V2",
    PHP_RESTART_FAILED_V2: "PHP_RESTART_FAILED_V2",
    NGINX_RESTART_V2: "NGINX_RESTART_V2",
    NGINX_RESTART_SUCCESS_V2: "NGINX_RESTART_SUCCESS_V2",
    NGINX_RESTART_FAILED_V2: "NGINX_RESTART_FAILED_V2",
};

export default OPERATION;
