const DOMAIN = {
    DOMAIN_GET: "DOMAIN_GET",
    DOMAIN_GET_SUCCESS: "DOMAIN_GET_SUCCESS",
    DOMAIN_GET_FAILED: "DOMAIN_GET_FAILED",
    DOMAIN_PUT: "DOMAIN_PUT",
    DOMAIN_PUT_SUCCESS: "DOMAIN_PUT_SUCCESS",
    DOMAIN_PUT_FAILED: "DOMAIN_PUT_FAILED",
    SEARCH_GET: "SEARCH_GET",
    SEARCH_GET_SUCCESS: "SEARCH_GET_SUCCESS",
    SEARCH_GET_FAILED: "SEARCH_GET_FAILED",
};

export default DOMAIN;
