const AFFILIATE_PROFILE = {
    AFFILIATE_PROFILE_PUT: "AFFILIATE_PROFILE_PUT",
    AFFILIATE_PROFILE_PUT_SUCCESS: "AFFILIATE_PROFILE_PUT_SUCCESS",
    AFFILIATE_PROFILE_PUT_FAILED: "AFFILIATE_PROFILE_PUT_FAILED",
};

export default AFFILIATE_PROFILE;
