const OPERATION = {
    CACHE_ALL_CLEAR_V6: "CACHE_ALL_CLEAR_V6",
    CACHE_ALL_CLEAR_V6_SUCCESS: "CACHE_ALL_CLEAR_V6_SUCCESS",
    CACHE_ALL_CLEAR_V6_FAILED: "CACHE_ALL_CLEAR_V6_FAILED",
};

export default OPERATION;
