const SSL = {
    SSL_PUT: "SSL_PUT",
    SSL_PUT_SUCCESS: "SSL_PUT_SUCCESS",
    SSL_PUT_FAILED: "SSL_PUT_FAILED",
    SSL_DELETE: "SSL_DELETE",
    SSL_DELETE_SUCCESS: "SSL_DELETE_SUCCESS",
    SSL_DELETE_FAILED: "SSL_DELETE_FAILED",
    SSL_RENEW: "SSL_RENEW",
    SSL_RENEW_SUCCESS: "SSL_RENEW_SUCCESS",
    SSL_RENEW_FAILED: "SSL_RENEW_FAILED",
};

export default SSL;
