const STRIPE = {
    // Create
    STRIPE_CREATE: "STRIPE_CREATE",
    STRIPE_CREATE_SUCCESS: "STRIPE_CREATE_SUCCESS",
    STRIPE_CREATE_FAILED: "STRIPE_CREATE_FAILED",
    // Delete 
    // STRIPE_DELETE: "STRIPE_DELETE",
    // STRIPE_DELETE_SUCCESS: "STRIPE_DELETE_SUCCESS",
    // STRIPE_DELETE_FAILED: "STRIPE_DELETE_FAILED",
    // // List 
    // STRIPE_LIST: "STRIPE_LIST",
    // STRIPE_LIST_SUCCESS: "STRIPE_LIST_SUCCESS",
    // STRIPE_LIST_FAILED: "STRIPE_LIST_FAILED",
    // // Edit 
    // STRIPE_EDIT: "STRIPE_EDIT",
    // STRIPE_EDIT_SUCCESS: "STRIPE_EDIT_SUCCESS",
    // STRIPE_EDIT_FAILED: "STRIPE_EDIT_FAILED",
    
    // // PAGINATION 
    // SERVICE_PAGINATION: "SERVICE_PAGINATION",
    // SERVICE_PAGINATION_SUCCESS: "SERVICE_PAGINATION_SUCCESS",
    // SERVICE_PAGINATION_FAILED: "SERVICE_PAGINATION_FAILED",
    // // CATALOG STATUS 
    // SERVICE_CATALOG: "SERVICE_CATALOG",
    // SERVICE_CATALOG_SUCCESS: "SERVICE_CATALOG_SUCCESS",
    // SERVICE_CATALOG_FAILED: "SERVICE_CATALOG_FAILED",
    // // SERVICE STATUS 
    // SERVICE_STATUS: "SERVICE_STATUS",
    // SERVICE_STATUS_SUCCESS: "SERVICE_STATUS_SUCCESS",
    // SERVICE_STATUS_FAILED: "SERVICE_STATUS_FAILED",
}

export default STRIPE;