const INSTANT = {
    INSTANT_DELETE_V3: "INSTANT_DELETE_V3",
    INSTANT_DELETE_SUCCESS_V3: "INSTANT_DELETE_SUCCESS_V3",
    INSTANT_DELETE_FAILED_V3: "INSTANT_DELETE_FAILED_V3",
};

export default INSTANT;
