const SNAPSHOT = {
    SNAPSHOT_GET: "SNAPSHOT_GET",
    SNAPSHOT_GET_SUCCESS: "SNAPSHOT_GET_SUCCESS",
    SNAPSHOT_MERGE: "SNAPSHOT_MERGE",
    SNAPSHOT_GET_FAILED: "SNAPSHOT_GET_FAILED",
    SNAPSHOT_POST: "SNAPSHOT_POST",
    SNAPSHOT_POST_SUCCESS: "SNAPSHOT_POST_SUCCESS",
    SNAPSHOT_POST_FAILED: "SNAPSHOT_POST_FAILED",
    SNAPSHOT_RESTORE: "SNAPSHOT_RESTORE",
    SNAPSHOT_RESTORE_SUCCESS: "SNAPSHOT_RESTORE_SUCCESS",
    SNAPSHOT_RESTORE_FAILED: "SNAPSHOT_RESTORE_FAILED",
};

export default SNAPSHOT;
