const CARD = {
    CARD_POST_V6: "CARD_POST_V6",
    CARD_POST_V6_SUCCESS: "CARD_POST_V6_SUCCESS",
    CARD_POST_V6_FAILED: "CARD_POST_V6_FAILED",
    CARD_DELETE_V6: "CARD_DELETE_V6",
    CARD_DELETE_V6_SUCCESS: "CARD_DELETE_V6_SUCCESS",
    CARD_DELETE_V6_FAILED: "CARD_DELETE_V6_FAILED",
    CARD_PUT_V6: "CARD_PUT_V6",
    CARD_PUT_V6_SUCCESS: "CARD_PUT_V6_SUCCESS",
    CARD_PUT_V6_FAILED: "CARD_PUT_V6_FAILED",
    // Update ( not status update )
    CARD_PUT_INFO_V6: "CARD_PUT_INFO_V6",
    CARD_PUT_INFO_V6_SUCCESS: "CARD_PUT_INFO_V6_SUCCESS",
    CARD_PUT_INFO_V6_FAILED: "CARD_PUT_INFO_V6_FAILED",
};

export default CARD;
