const SSL_ACTION_TYPE = {
    GET_SSL: "GET_SSL",
    GET_SSL_SUCCESS: "GET_SSL_SUCCESS",
    GET_SSL_FAILED: "GET_SSL_FAILED",

    ENABLE_SSL: "ENABLE_SSL",
    ENABLE_SSL_SUCCESS: "ENABLE_SSL_SUCCESS",
    ENABLE_SSL_FAILED: "ENABLE_SSL_FAILED",

    DISABLE_SSL: "DISABLE_SSL",
    DISABLE_SSL_SUCCESS: "DISABLE_SSL_SUCCESS",
    DISABLE_SSL_FAILED: "DISABLE_SSL_FAILED",

    PUT_SSL: "PUT_SSL",
    PUT_SSL_SUCCESS: "PUT_SSL_SUCCESS",
    PUT_SSL_FAILED: "PUT_SSL_FAILED",
};

export default SSL_ACTION_TYPE;
