const OPERATION = {
    PHP_RESTART: "PHP_RESTART",
    PHP_RESTART_SUCCESS: "PHP_RESTART_SUCCESS",
    PHP_RESTART_FAILED: "PHP_RESTART_FAILED",
    PERMISSION_RESET: "PERMISSION_RESET",
    PERMISSION_RESET_SUCCESS: "PERMISSION_RESET_SUCCESS",
    PERMISSION_RESET_FAILED: "PERMISSION_RESET_FAILED",
    CACHE_CLEAR: "CACHE_CLEAR",
    CACHE_CLEAR_SUCCESS: "CACHE_CLEAR_SUCCESS",
    CACHE_CLEAR_FAILED: "CACHE_CLEAR_FAILED",
    CACHE_ALL_CLEAR: "CACHE_ALL_CLEAR",
    CACHE_ALL_CLEAR_SUCCESS: "CACHE_ALL_CLEAR_SUCCESS",
    CACHE_ALL_CLEAR_FAILED: "CACHE_ALL_CLEAR_FAILED",
    NGINX_RESTART: "NGINX_RESTART",
    NGINX_RESTART_SUCCESS: "NGINX_RESTART_SUCCESS",
    NGINX_RESTART_FAILED: "NGINX_RESTART_FAILED",
};

export default OPERATION;
