const WORDPRESS = {
    WORDPRESS_UPDATE_V6: "WORDPRESS_UPDATE_V6",
    WORDPRESS_UPDATE_V6_SUCCESS: "WORDPRESS_UPDATE_V6_SUCCESS",
    WORDPRESS_UPDATE_V6_FAILED: "WORDPRESS_UPDATE_V6_FAILED",
    WORDPRESS_UPDATE_ALL_V6: "WORDPRESS_UPDATE_ALL_V6",
    WORDPRESS_UPDATE_ALL_V6_SUCCESS: "WORDPRESS_UPDATE_ALL_V6_SUCCESS",
    WORDPRESS_UPDATE_ALL_V6_FAILED: "WORDPRESS_UPDATE_ALL_V6_FAILED",
    WORDPRESS_LOCK_V6: "WORDPRESS_LOCK_V6",
    WORDPRESS_LOCK_V6_SUCCESS: "WORDPRESS_LOCK_V6_SUCCESS",
    WORDPRESS_LOCK_V6_FAILED: "WORDPRESS_LOCK_V6_FAILED",
    WORDPRESS_REFRESH_V6: "WORDPRESS_REFRESH_V6",
    WORDPRESS_REFRESH_V6_SUCCESS: "WORDPRESS_REFRESH_V6_SUCCESS",
    WORDPRESS_REFRESH_V6_FAILED: "WORDPRESS_REFRESH_V6_FAILED",
};

export default WORDPRESS;
