const SITE_ACTION_TYPE = {
    GET_SITES: "GET_SITES",
    GET_SITES_SUCCESS: "GET_SITES_SUCCESS",
    GET_SITE_DETAIL: "GET_SITE_DETAIL",
    GET_SITE_DETAIL_SUCCESS: "GET_SITE_DETAIL_SUCCESS",
    QUICK_LOGIN: "QUICK_LOGIN",
    QUICK_LOGIN_SUCCESS: "QUICK_LOGIN_SUCCESS",
    POST_SFTP: "POST_SFTP",
    POST_SFTP_SUCCESS: "POST_SFTP_SUCCESS",
    QUICK_LOGIN_FAILED: "QUICK_LOGIN_FAILED",
    POST_SFTP_FAILED: "POST_SFTP_FAILED",
    RETEST_PAGESPEED: "RETEST_PAGESPEED",
    RETEST_PAGESPEED_SUCCESS: "RETEST_PAGESPEED_SUCCESS",
    RETEST_PAGESPEED_FAILED: "RETEST_PAGESPEED_FAILED",
    UP_TIME_REPORT: "UP_TIME_REPORT",
    UP_TIME_REPORT_SUCCESS: "UP_TIME_REPORT_SUCCESS",
    UP_TIME_REPORT_FAILED: "UP_TIME_REPORT_FAILED",
};

export default SITE_ACTION_TYPE;
