const DOMAIN = {
    DOMAIN_PUT_V6: "DOMAIN_PUT_V6",
    DOMAIN_PUT_V6_SUCCESS: "DOMAIN_PUT_V6_SUCCESS",
    DOMAIN_PUT_V6_FAILED: "DOMAIN_PUT_V6_FAILED",
    DOMAIN_POST_V6: "DOMAIN_POST_V6",
    DOMAIN_POST_V6_SUCCESS: "DOMAIN_POST_V6_SUCCESS",
    DOMAIN_POST_V6_FAILED: "DOMAIN_POST_V6_FAILED",
    DOMAIN_DELETE_V6: "DOMAIN_DELETE_V6",
    DOMAIN_DELETE_V6_SUCCESS: "DOMAIN_DELETE_V6_SUCCESS",
    DOMAIN_DELETE_V6_FAILED: "DOMAIN_DELETE_V6_FAILED",
};

export default DOMAIN;
