const FEATURE = {
    WORDPRESS_LOGIN_V3: "WORDPRESS_LOGIN_V3",
    WORDPRESS_LOGIN_SUCCESS_V3: "WORDPRESS_LOGIN_SUCCESS_V3",
    WORDPRESS_LOGIN_FAILED_V3: "WORDPRESS_LOGIN_FAILED_V3",
};

export default FEATURE;
