const STAGING = {
    STAGING_POST_V6: "STAGING_POST_V6",
    STAGING_POST_V6_SUCCESS: "STAGING_POST_V6_SUCCESS",
    STAGING_POST_V6_FAILED: "STAGING_POST_V6_FAILED",
    SYNC_PUSH_LIVE_V6: "SYNC_PUSH_LIVE_V6",
    SYNC_PUSH_LIVE_V6_SUCCESS: "SYNC_PUSH_LIVE_V6_SUCCESS",
    SYNC_PUSH_LIVE_V6_FAILED: "SYNC_PUSH_LIVE_V6_FAILED",
};

export default STAGING;
