const NITRO = {
    NITRO_FIRST: "NITRO_FIRST",
    NITRO_FIRST_SUCCESS: "NITRO_FIRST_SUCCESS",
    NITRO_FIRST_FAILED: "NITRO_FIRST_FAILED",
    NITRO_ENABLE: "NITRO_ENABLE",
    NITRO_ENABLE_SUCCESS: "NITRO_ENABLE_SUCCESS",
    NITRO_ENABLE_FAILED: "NITRO_ENABLE_FAILED",
    NITRO_DISABLE: "NITRO_DISABLE",
    NITRO_DISABLE_SUCCESS: "NITRO_DISABLE_SUCCESS",
    NITRO_DISABLE_FAILED: "NITRO_DISABLE_FAILED",
};

export default NITRO;
