const REGISTER = {
    REGISTRATION_POST: "REGISTRATION_POST",
    REGISTRATION_POST_SUCCESS: "REGISTRATION_POST_SUCCESS",
    REGISTRATION_POST_FAILED: "REGISTRATION_POST_FAILED",
};

export default REGISTER;
