const SITE = {
    SITE_PORTAL_SETTINGS_GET_V6: "SITE_PORTAL_SETTINGS_GET_V6",
    SITE_PORTAL_SETTINGS_GET_V6_SUCCESS: "SITE_PORTAL_SETTINGS_GET_V6_SUCCESS",
    SITE_PORTAL_SETTINGS_GET_V6_FAILED: "SITE_PORTAL_SETTINGS_GET_V6_FAILED",
};

export default SITE;
