const V1 = {
    login: 'v1/auth/user-login/',
    register: 'v1/auth/register-customer/',
    forgot_password: 'v1/auth/forget-password',
    dashboard: 'v1/dashboard/',
    products: 'v1/products/',
    sites: 'v1/sites/',
    site_operation: {
        reset_sftp: 'v1/sites/reset-sftp/',
        generate_sftp: 'v1/sites/generate-sftp/',
        costing: 'v1/sites/costing/',
        restart_nginx: 'v1/sites/restart-servers/',
        restart_php: 'v1/sites/restart-servers/',
        reset_permission: 'v1/sites/reset-permissions/',
        plugin_key: 'v1/wp/generate-key/',
        backup: 'v1/sites/backups',
        site_delete: 'v1/sites/request/',
        site_delete_cancel: 'v1/sites/revoke/',
        clear_all_cache: 'v1/sites/clear-caches/',
        quick_login: 'v1/sites/one-click-login/',
    },
    billing: {
        invoice: 'v1/invoice',
        card: 'v1/payment/card',
    },
    wordpress: {
        details: 'v1/sites/wp/',
        update: 'v1/sites/update-wp/',
        lock: 'v1/sites/wp/',
        update_all: 'v1/wordpress/content',
        update_all_containers: 'v1/wordpress/all-containers',
        updates_on_icon: 'v1/wordpress/refresh/',
        updates_all_v1: 'v1/sites/wp/content/',
        timeline: 'v1/sites/wp/timeline/',
    },
    cdn: {
        details: 'v1/sites/cdn-details/',
        enable: 'v1/sites/enable-cdn/',
        disable: 'v1/sites/disable-cdn/',
        update: 'v1/sites/cdn-update/',
        purge_cache: 'v1/site/cdn/cache/',
    },
    ssl: {
        enable: 'v1/sites/ssl-enable/',
        get: 'v1/sites/ssl/',
        renew: 'v1/sites/ssl-renew/',
        disable: 'v1/sites/ssl-disable/',
    },
    domain: {
        restful: 'v1/sites/domains/',
        primary: 'v1/sites/domains/primary/',
    },
    nitro: {
        details: 'v1/site/nitro/',
        enable: 'v1/site/nitro/enable/',
        disable: 'v1/site/nitro/disable/',
    },
    clear_cache: 'v1/site/clear-cache/',
    one_click_php: 'v1/site/phpmyadmin/',
    force_redirect: 'v1/site/domain/force/',
    top_up: 'v1/wallet/topup/',
    restore: {
        snapshot: 'v1/site/restore/backup/',
    },
    backup: {
        create: 'v1/site/backup/',
        file: 'v1/sites/backups/',
        file_restore: 'v1/sites/backups/',
        download_backup: 'v1/sites/backups/download/',
    },
    identity: 'v1/sites/new-identity',
    region: 'v1/regions/',
    services: 'v1/services/',
    access_sharing: 'v1/sites/access-sharing/',
    clone: 'v1/sites/clone/',
    site_db: 'v1/sitesdb',
    screenshot_put: 'v1/sites/screenshot/',
    affiliate: {
        stats: 'v1/affiliate/stats',
        wallet: 'v1/affiliate/wallet',
        click: 'affiliate/clicks/',
        profile: 'v1/affiliate/paypal',
    },
    profile: 'v1/profiles',
    staging: 'v1/sites/staging',
    staging_delete: 'v1/sites/',
    sync_environment: 'v1/sites/staging/sync/',
    staging_renewal: 'v1/sites/renewal/',
    addon: 'v1/sites/addon/',
    notification: 'notification/',
    settings: {
        whiteLabelGet: 'v1/white-label/',
        whiteLabelPost: 'v1/white-label',
    },
    logout: 'v1/logout',
    verification_resend: 'v1/verification',
    retest_pagespeed: 'v1/sites/page-speed-after/',
    cloud_provider: 'v1/cloud-providers',
    staging_logs: 'v1/sites/api/staging-logs/',
    clone_form: 'v1/sites/clone/',
    change_password: '/v1/change-password',
    up_time_report: 'v1/sites/betteruptime/',
};

export default V1;
