const V6 = {
    sites: 'v6/sites/',
    regions: 'v6/regions',
    plans: 'v6/site-plans',
    products: 'v6/products/',
    domain: 'v6/domain-validate',
    customer_detail : 'v6/sites/customer-details/',
    site_operation: {
        backup: 'v6/backups/',
        clear_all_cache: 'v6/sites/clear-cache/',
        site_delete: 'v6/sites/request-delete-site/',
        site_delete_cancel: 'v6/sites/cancel-request-delete-site/',
        site_delete_instant: 'v6/sites/delete-staging-instantly/',
        reset_sftp: 'v6/sites/reset-sftp/',
        download_backup: 'v6/backups/download/',
        restore_backup: 'v6/backups/restore/',
    },
    resources: 'v6/sites-resources/',
    site_db: 'v6/sites-db-details/',
    site_wp: 'v6/sites-wordpress/',
    site_pagespeed: 'v6/sites-page-speed/',
    site_version: 'v6/sites/update-php-version/',
    site_otp: {
        list: 'v6/sites/otp/',
        update: 'v6/sites/otp/',
    },
    refresh_pagespeed: 'v6/site-speed/refresh/',
    enable_pagespeed: 'v6/enable-page-speed/',
    wp_login: 'v6/sites/one-click-login/',
    access_sharing: 'v6/sites/access-sharing/',
    wordpress: {
        update: 'v6/sites/wp/content/',
        lock: 'v6/sites/wp/',
        updates_on_icon: 'v6/wordpress/refresh/',
    },
    staging: 'v6/sites/staging/',
    unlimited_edits: 'v6/sites/addon/unlimited-edits/',
    domains: {
        restful: 'v6/sites/domains/',
        primary: 'v6/sites/domains/primary/',
    },
    db_login: 'v6/sites/one-click-login-db/',
    clone_form: 'v6/sites/clone/',
    billing: {
        invoice: 'v6/invoice',
        card: 'v6/payment/card',
        updateCard: 'v6/payment/card',
    },
    whiteLabel: {
        create: 'v6/white-label',
        updateSSL: 'v6/enable-ssl',
        get: 'v6/white-label',
    },
    auth: {
        login: 'v6/auth/login',
        register: 'v6/auth/register',
    },
    portal_settings: 'v6/portal-settings',
    // Domain: window.location.hostname,
    // Domain: '51blocks.saasfaapp.com',
    // Domain:"1234.com",
    Domain: 'customer-dev.bionicwp.dev',
    custom_plan: {
        list: 'v6/custom-plan',
        edit: 'v6/custom-plan',
        delete: 'v6/custom-plan',
        create: 'v6/custom-plan',
    },
    stripe: {
        create: 'v6/stripe',
    },
};

export default V6;
