const BACKUP = {
    BACKUP_GET: "BACKUP_GET",
    BACKUP_GET_SUCCESS: "BACKUP_GET_SUCCESS",
    BACKUP_GET_FAILED: "BACKUP_GET_FAILED",
    BACKUP_POST: "BACKUP_POST",
    BACKUP_POST_SUCCESS: "BACKUP_POST_SUCCESS",
    BACKUP_POST_FAILED: "BACKUP_POST_FAILED",
    BACKUP_MERGE: "BACKUP_MERGE",
    BACKUP_RESTORE: "BACKUP_RESTORE",
    BACKUP_RESTORE_SUCCESS: "BACKUP_RESTORE_SUCCESS",
    BACKUP_RESTORE_FAILED: "BACKUP_RESTORE_FAILED",
    BACKUP_DOWNLOAD: "BACKUP_DOWNLOAD",
    BACKUP_DOWNLOAD_SUCCESS: "BACKUP_DOWNLOAD_SUCCESS",
    BACKUP_DOWNLOAD_FAILED: "BACKUP_DOWNLOAD_FAILED",
};

export default BACKUP;
