const BACKUP = {
    BACKUP_GET_V6: "BACKUP_GET_V6",
    BACKUP_GET_V6_SUCCESS: "BACKUP_GET_V6_SUCCESS",
    BACKUP_GET_V6_FAILED: "BACKUP_GET_V6_FAILED",
    BACKUP_DOWNLOAD_V6: "BACKUP_DOWNLOAD_V6",
    BACKUP_DOWNLOAD_SUCCESS_V6: "BACKUP_DOWNLOAD_SUCCESS_V6",
    BACKUP_DOWNLOAD_FAILED_V6: "BACKUP_DOWNLOAD_FAILED_V6",
    BACKUP_RESTORE_V6: "BACKUP_RESTORE_V6",
    BACKUP_RESTORE_SUCCESS_V6: "BACKUP_RESTORE_SUCCESS_V6",
    BACKUP_RESTORE_FAILED_V6: "BACKUP_RESTORE_FAILED_V6",
};

export default BACKUP;
