const DASHBOARD_ACTION_TYPE = {
    GET_DASHBOARD: "GET_DASHBOARD",
    GET_DASHBOARD_SCCUESS: "GET_DASHBOARD_SCCUESS",
    GET_DASHBOARD_FAIL: "GET_DASHBOARD_FAIL",
};

export default DASHBOARD_ACTION_TYPE;
