const CUSTOM_PLAN = {
    // Create
    CUSTOM_PLAN_CREATE: "CUSTOM_PLAN_CREATE",
    CUSTOM_PLAN_CREATE_SUCCESS: "CUSTOM_PLAN_CREATE_SUCCESS",
    CUSTOM_PLAN_CREATE_FAILED: "CUSTOM_PLAN_CREATE_FAILED",
    // Delete 
    CUSTOM_PLAN_DELETE: "CUSTOM_PLAN_DELETE",
    CUSTOM_PLAN_DELETE_SUCCESS: "CUSTOM_PLAN_DELETE_SUCCESS",
    CUSTOM_PLAN_DELETE_FAILED: "CUSTOM_PLAN_DELETE_FAILED",
    // List 
    CUSTOM_PLAN_LIST: "CUSTOM_PLAN_LIST",
    CUSTOM_PLAN_LIST_SUCCESS: "CUSTOM_PLAN_LIST_SUCCESS",
    CUSTOM_PLAN_LIST_FAILED: "CUSTOM_PLAN_LIST_FAILED",
    // Edit 
    CUSTOM_PLAN_EDIT: "CUSTOM_PLAN_EDIT",
    CUSTOM_PLAN_EDIT_SUCCESS: "CUSTOM_PLAN_EDIT_SUCCESS",
    CUSTOM_PLAN_EDIT_FAILED: "CUSTOM_PLAN_EDIT_FAILED",
    
    // // PAGINATION 
    // SERVICE_PAGINATION: "SERVICE_PAGINATION",
    // SERVICE_PAGINATION_SUCCESS: "SERVICE_PAGINATION_SUCCESS",
    // SERVICE_PAGINATION_FAILED: "SERVICE_PAGINATION_FAILED",
    // // CATALOG STATUS 
    // SERVICE_CATALOG: "SERVICE_CATALOG",
    // SERVICE_CATALOG_SUCCESS: "SERVICE_CATALOG_SUCCESS",
    // SERVICE_CATALOG_FAILED: "SERVICE_CATALOG_FAILED",
    // // SERVICE STATUS 
    // SERVICE_STATUS: "SERVICE_STATUS",
    // SERVICE_STATUS_SUCCESS: "SERVICE_STATUS_SUCCESS",
    // SERVICE_STATUS_FAILED: "SERVICE_STATUS_FAILED",
}

export default CUSTOM_PLAN;