const AFFILIATE = {
    AFFILIATE_CLICK: "AFFILIATE_CLICK",
    AFFILIATE_CLICK_SUCCESS: "AFFILIATE_CLICK_SUCCESS",
    AFFILIATE_CLICK_FAILED: "AFFILIATE_CLICK_FAILED",
    AFFILIATE_STATS: "AFFILIATE_STATS",
    AFFILIATE_STATS_SUCCESS: "AFFILIATE_STATS_SUCCESS",
    AFFILIATE_STATS_FAILED: "AFFILIATE_STATS_FAILED",
    AFFILIATE_WALLET: "AFFILIATE_WALLET",
    AFFILIATE_WALLET_SUCCESS: "AFFILIATE_WALLET_SUCCESS",
    AFFILIATE_WALLET_FAILED: "AFFILIATE_WALLET_FAILED",
};

export default AFFILIATE;
