const STAGING = {
    STAGING_POST: "STAGING_POST",
    STAGING_POST_SUCCESS: "STAGING_POST_SUCCESS",
    STAGING_POST_FAILED: "STAGING_POST_FAILED",
    STAGING_DELETE: "STAGING_DELETE",
    STAGING_DELETE_SUCCESS: "STAGING_DELETE_SUCCESS",
    STAGING_DELETE_FAILED: "STAGING_DELETE_FAILED",
    SYNC_PUT: "SYNC_PUT",
    SYNC_PUT_SUCCESS: "SYNC_PUT_SUCCESS",
    SYNC_PUT_FAILED: "SYNC_PUT_FAILED",
    STAGING_RENEWAL: "STAGING_RENEWAL",
    STAGING_RENEWAL_SUCCESS: "STAGING_RENEWAL_SUCCESS",
    STAGING_RENEWAL_FAILED: "STAGING_RENEWAL_FAILED",
    STAGING_LOGS: "STAGING_LOGS",
    STAGING_LOGS_SUCCESS: "STAGING_LOGS_SUCCESS",
    STAGING_LOGS_FAILED: "STAGING_LOGS_FAILED",
    SYNC_PUSH_LIVE: "SYNC_PUSH_LIVE",
    SYNC_PUSH_LIVE_SUCCESS: "SYNC_PUSH_LIVE_SUCCESS",
    SYNC_PUSH_LIVE_FAILED: "SYNC_PUSH_LIVE_FAILED",
};

export default STAGING;
