const CDN = {
    CDN_ENABLE_V2: "CDN_ENABLE_V2",
    CDN_ENABLE_SUCCESS_V2: "CDN_ENABLE_SUCCESS_V2",
    CDN_ENABLE_FAILED_V2: "CDN_ENABLE_FAILED_V2",
    CDN_DISABLE_V2: "CDN_DISABLE_V2",
    CDN_DISABLE_SUCCESS_V2: "CDN_DISABLE_SUCCESS_V2",
    CDN_DISABLE_FAILED_V2: "CDN_DISABLE_FAILED_V2",
    CDN_PUT_V2: "CDN_PUT_V2",
    CDN_PUT_SUCCESS_V2: "CDN_PUT_SUCCESS_V2",
    CDN_PUT_FAILED_V2: "CDN_PUT_FAILED_V2",
};

export default CDN;
