const SITE = {
    SITE_VERSION_PUT_V6: "SITE_VERSION_PUT_V6",
    SITE_VERSION_PUT_V6_SUCCESS: "SITE_VERSION_PUT_V6_SUCCESS",
    SITE_VERSION_PUT_V6_FAILED: "SITE_VERSION_PUT_V6_FAILED",

    // SITE_POST_V6: "SITE_POST_V6",
    // SITE_POST_V6_SUCCESS: "SITE_POST_V6_SUCCESS",
    // SITE_POST_V6_FAILED: "SITE_POST_V6_FAILED",
    // SITE_DELETE_V6: "SITE_DELETE_V6",
    // SITE_DELETE_V6_SUCCESS: "SITE_DELETE_V6_SUCCESS",
    // SITE_DELETE_V6_FAILED: "SITE_DELETE_V6_FAILED",
};

export default SITE;
