const NOTIFICATION = {
    NOTIFICATION_GET: "NOTIFICATION_GET",
    NOTIFICATION_GET_SUCCESS: "NOTIFICATION_GET_SUCCESS",
    NOTIFICATION_GET_FAILED: "NOTIFICATION_GET_FAILED",
    NOTIFICATION_READ: "NOTIFICATION_READ",
    NOTIFICATION_READ_SUCCESS: "NOTIFICATION_READ_SUCCESS",
    NOTIFICATION_READ_FAILED: "NOTIFICATION_READ_FAILED",
    NOTIFICATION_LIST: "NOTIFICATION_LIST",
    NOTIFICATION_LIST_SUCCESS: "NOTIFICATION_LIST_SUCCESS",
    NOTIFICATION_LIST_FAILED: "NOTIFICATION_LIST_FAILED",
};

export default NOTIFICATION;
