const FEATURE = {
    ACCESS_SHARING_V2: "ACCESS_SHARING_V2",
    ACCESS_SHARING_SUCCESS_V2: "ACCESS_SHARING_SUCCESS_V2",
    ACCESS_SHARING_FAILED_V2: "ACCESS_SHARING_FAILED_V2",
};

export default FEATURE;
