const AUTH_V4 = {
    LOGIN_V4: "LOGIN_V4",
    LOGIN_SUCCESS_V4: "LOGIN_SUCCESS_V4",
    LOGIN_FAILED_V4: "LOGIN_FAILED_V4",
    REGISTRATION_V4: "REGISTRATION_V4",
    REGISTRATION_SUCCESS_V4: "REGISTRATION_SUCCESS_V4",
    REGISTRATION_FAILED_V4: "REGISTRATION_FAILED_V4",
};

export default AUTH_V4;
