const AUTH_V6 = {
    LOGIN_V6: "LOGIN_V6",
    LOGIN_SUCCESS_V6: "LOGIN_SUCCESS_V6",
    LOGIN_FAILED_V6: "LOGIN_FAILED_V6",
    REGISTRATION_V6: "REGISTRATION_V6",
    REGISTRATION_SUCCESS_V6: "REGISTRATION_SUCCESS_V6",
    REGISTRATION_FAILED_V6: "REGISTRATION_FAILED_V6",
};

export default AUTH_V6;
