const INVOICE = {
    INVOICE_GET: "INVOICE_GET",
    INVOICE_GET_SUCCESS: "INVOICE_GET_SUCCESS",
    INVOICE_GET_FAILED: "INVOICE_GET_FAILED",
    INVOICE_FIRST: "INVOICE_FIRST",
    INVOICE_FIRST_SUCCESS: "INVOICE_FIRST_SUCCESS",
    INVOICE_FIRST_FAILED: "INVOICE_FIRST_FAILED",
    INVOICE_PUT: "INVOICE_PUT",
    INVOICE_PUT_SUCCESS: "INVOICE_PUT_SUCCESS",
    INVOICE_PUT_FAILED: "INVOICE_PUT_FAILED",
};

export default INVOICE;
