const DOMAIN_ACTION_TYPE = {
    GET_DOMAIN: "GET_DOMAIN",
    GET_DOMAIN_SUCCESS: "GET_DOMAIN_SUCCESS",
    GET_DOMAIN_FAILED: "GET_DOMAIN_FAILED",
    POST_DOMAIN: "POST_DOMAIN",
    POST_DOMAIN_SUCCESS: "POST_DOMAIN_SUCCESS",
    POST_DOMAIN_FAILED: "POST_DOMAIN_FAILED",
    DELETE_DOMAIN: "DELETE_DOMAIN",
    DELETE_DOMAIN_SUCCESS: "DELETE_DOMAIN_SUCCESS",
    DELETE_DOMAIN_FAILED: "DELETE_DOMAIN_FAILED",
};

export default DOMAIN_ACTION_TYPE;
