const SETTINGS = {
    NERD_MODE: "NERD_MODE",
    NERD_MODE_SUCCESS: "NERD_MODE_SUCCESS",
    NERD_MODE_FAILED: "NERD_MODE_FAILED",
    SERVICE_GET: "SERVICE_GET",
    SERVICE_GET_SUCCESS: "SERVICE_GET_SUCCESS",
    SERVICE_GET_FAILED: "SERVICE_GET_FAILED",
    WHITE_LABEL_TOGGLE: "WHITE_LABEL_TOGGLE",
    WHITE_LABEL_TOGGLE_SUCCESS: "WHITE_LABEL_TOGGLE_SUCCESS",
    WHITE_LABEL_TOGGLE_FAILED: "WHITE_LABEL_TOGGLE_FAILED",
    WHITE_LABEL_GET: "WHITE_LABEL_GET",
    WHITE_LABEL_GET_SUCCESS: "WHITE_LABEL_GET_SUCCESS",
    WHITE_LABEL_GET_FAILED: "WHITE_LABEL_GET_FAILED",
    WHITE_LABEL_POST: "WHITE_LABEL_POST",
    WHITE_LABEL_POST_SUCCESS: "WHITE_LABEL_POST_SUCCESS",
    WHITE_LABEL_POST_FAILED: "WHITE_LABEL_POST_FAILED",
};

export default SETTINGS;
