const BACKUP = {
    BACKUP_POST_V2: "BACKUP_POST_V2",
    BACKUP_POST_SUCCESS_V2: "BACKUP_POST_SUCCESS_V2",
    BACKUP_POST_FAILED_V2: "BACKUP_POST_FAILED_V2",
    BACKUP_MERGE_V2: "BACKUP_MERGE_V2",
    BACKUP_RESTORE_V2: "BACKUP_RESTORE_V2",
    BACKUP_RESTORE_SUCCESS_V2: "BACKUP_RESTORE_SUCCESS_V2",
    BACKUP_RESTORE_FAILED_V2: "BACKUP_RESTORE_FAILED_V2",
    BACKUP_DOWNLOAD_V2: "BACKUP_DOWNLOAD_V2",
    BACKUP_DOWNLOAD_SUCCESS_V2: "BACKUP_DOWNLOAD_SUCCESS_V2",
    BACKUP_DOWNLOAD_FAILED_V2: "BACKUP_DOWNLOAD_FAILED_V2",
};

export default BACKUP;
