const ADDON = {
    UNLIMITED_EDITS_V6: "UNLIMITED_EDITS_V6",
    UNLIMITED_EDITS_V6_SUCCESS: "UNLIMITED_EDITS_V6_SUCCESS",
    UNLIMITED_EDITS_V6_FAILED: "UNLIMITED_EDITS_V6_FAILED",
};

export default ADDON;
