const ADDON = {
    ADDON_GET: "ADDON_GET",
    ADDON_GET_SUCCESS: "ADDON_GET_SUCCESS",
    ADDON_GET_FAILED: "ADDON_GET_FAILED",
    ADDON_TOGGLE: "ADDON_TOGGLE",
    ADDON_TOGGLE_SUCCESS: "ADDON_TOGGLE_SUCCESS",
    ADDON_TOGGLE_FAILED: "ADDON_TOGGLE_FAILED",
};

export default ADDON;
