const AUTHV2 = {
    ACCOUNT_VERIFICATION_V2: "ACCOUNT_VERIFICATION_V2",
    ACCOUNT_VERIFICATION_SUCCESS_V2: "ACCOUNT_VERIFICATION_SUCCESS_V2",
    ACCOUNT_VERIFICATION_FAILED_V2: "ACCOUNT_VERIFICATION_FAILED_V2",
};

export default AUTHV2;
