const FEATURE = {
    ACCESS_SHARING_V6: "ACCESS_SHARING_V6",
    ACCESS_SHARING_V6_SUCCESS: "ACCESS_SHARING_V6_SUCCESS",
    ACCESS_SHARING_V6_FAILED: "ACCESS_SHARING_V6_FAILED",
    SITE_DB_LOGIN_V6: "SITE_DB_LOGIN_V6",
    SITE_DB_LOGIN_V6_SUCCESS: "SITE_DB_LOGIN_V6_SUCCESS",
    SITE_DB_LOGIN_V6_FAILED: "SITE_DB_LOGIN_V6_FAILED",
    SITE_SFTP_V6: "SITE_SFTP_V6",
    SITE_SFTP_V6_SUCCESS: "SITE_SFTP_V6_SUCCESS",
    SITE_SFTP_V6_FAILED: "SITE_SFTP_V6_FAILED",
    SITE_CLONE_FORM_V6: "SITE_CLONE_FORM_V6",
    SITE_CLONE_FORM_V6_SUCCESS: "SITE_CLONE_FORM_V6_SUCCESS",
    SITE_CLONE_FORM_V6_FAILED: "SITE_CLONE_FORM_V6_FAILED",
};

export default FEATURE;
