const SITE = {
    SITE_WHITE_LABEL_PUT_V6: "SITE_WHITE_LABEL_PUT_V6",
    SITE_WHITE_LABEL_PUT_V6_SUCCESS: "SITE_WHITE_LABEL_PUT_V6_SUCCESS",
    SITE_WHITE_LABEL_PUT_V6_FAILED: "SITE_WHITE_LABEL_PUT_V6_FAILED",

    SITE_WHITE_LABEL_POST_V6: "SITE_WHITE_LABEL_POST_V6",
    SITE_WHITE_LABEL_POST_V6_SUCCESS: "SITE_WHITE_LABEL_POST_V6_SUCCESS",
    SITE_WHITE_LABEL_POST_V6_FAILED: "SITE_WHITE_LABEL_POST_V6_FAILED",

    SITE_WHITE_LABEL_GET_V6: "SITE_WHITE_LABEL_GET_V6",
    SITE_WHITE_LABEL_GET_V6_SUCCESS: "SITE_WHITE_LABEL_GET_V6_SUCCESS",
    SITE_WHITE_LABEL_GET_V6_FAILED: "SITE_WHITE_LABEL_GET_V6_FAILED",

};

export default SITE;
